#!/bin/bash
# Script to help get OCIDs from OCI Console

echo "════════════════════════════════════════"
echo "📋 OCI Setup - Getting Your OCIDs"
echo "════════════════════════════════════════"
echo ""
echo "Follow these steps in OCI Console:"
echo ""
echo "1. USER OCID:"
echo "   - Click your user icon (top right)"
echo "   - Select 'User Settings'"
echo "   - Under 'User Information', find 'OCID'"
echo "   - Click the copy icon 📋"
echo ""
echo "2. TENANCY OCID:"
echo "   - Click hamburger menu ☰ (top left)"
echo "   - Go to: Administration → Tenancy Details"
echo "   - Under 'Tenancy Information', find 'OCID'"
echo "   - Click the copy icon 📋"
echo ""
echo "3. COMPARTMENT OCID (optional):"
echo "   - Click hamburger menu ☰"
echo "   - Go to: Identity & Security → Compartments"
echo "   - Click on your compartment (or create one)"
echo "   - Copy the OCID"
echo ""
echo "════════════════════════════════════════"
echo "After you have the OCIDs, run:"
echo "  oci setup config"
echo ""
echo "You'll be asked for:"
echo "  - User OCID"
echo "  - Tenancy OCID"
echo "  - Region (e.g., us-ashburn-1)"
echo "  - Private key path: ~/.oci/oci_api_key.pem"
echo "  - Fingerprint (from API key upload)"
echo "════════════════════════════════════════"

